"""Durable source-of-truth persistence (§ Phase B).

PostgreSQL is authoritative in production; SQLite is the local/test backend behind the same Store
interface. `open_store` selects a backend from a URL:
    postgres://…  / postgresql://…  -> PostgresStore
    sqlite:///path  or a bare path   -> SqliteStore
"""

from .base import (
    AiAssessmentComponentRow,
    AiAssessmentRow,
    AiGovernanceResultRow,
    AiPredictionOutcomeRow,
    AiPredictionRow,
    AnalystEstimatesRow,
    AuditEventRow,
    BacktestDecisionRow,
    BacktestEquityPointRow,
    BacktestEventRow,
    BacktestMetricsRow,
    BacktestRunRow,
    BacktestTradeRow,
    CompanyRow,
    DailyLossLockRow,
    DailyPnlRow,
    DataCompletenessRow,
    DecisionRow,
    FillRow,
    FinancialMetricsRow,
    FundamentalObservationRow,
    FundamentalSeriesInstrumentRow,
    FundamentalSeriesRow,
    FundamentalSourceRow,
    InsiderClusterRow,
    InsiderTransactionRow,
    InstitutionalChangeRow,
    InstrumentImportEventRow,
    InstrumentImportRunRow,
    InstrumentRow,
    KillSwitchRow,
    MacroEventRow,
    MacroSnapshotRow,
    MacroSourceRow,
    NewsImportEventRow,
    NewsImportRunRow,
    NewsItemRow,
    NewsMessageEventRow,
    NewsMessageInstrumentRow,
    NewsMessageRow,
    NewsSourceRow,
    OptionsFlowRow,
    OptionsSnapshotRow,
    OrderRow,
    PaperCanaryAccountRow,
    PaperCanaryConflict,
    PaperCanaryError,
    PaperCanaryFillCommitResult,
    PaperCanaryFillRow,
    PaperCanaryOrderEventRow,
    PaperCanaryOrderRow,
    PaperCanaryPositionRow,
    PaperCanaryReconciliationRow,
    PaperCanaryRunRow,
    PaperCanarySafetyError,
    PaperCanaryStateError,
    PositionRow,
    ResearchDatasetEventRow,
    ResearchDatasetRow,
    ResearchIntelInputRow,
    ResearchIntelOutcomeRow,
    ResearchIntelSnapshotRow,
    ResearchValidationRunRow,
    RiskConfigRow,
    RiskControlPolicyRow,
    RiskEventRow,
    RiskStateRow,
    RuntimeStateRow,
    SqlStore,
    Store,
    TraderPerformanceRow,
    TraderPositionRow,
    TraderRow,
    ValuationRow,
    new_id,
    paper_canary_config_checksum,
    paper_canary_request_checksum,
    risk_config_token,
    utcnow_iso,
)
from .money import D, money_str, to_decimal
from .schema import Migrator
from .sqlite_store import SqliteStore, open_sqlite

__all__ = [
    "AiAssessmentComponentRow",
    "AiAssessmentRow",
    "AiGovernanceResultRow",
    "AiPredictionOutcomeRow",
    "AiPredictionRow",
    "AnalystEstimatesRow",
    "AuditEventRow",
    "BacktestDecisionRow",
    "BacktestEquityPointRow",
    "BacktestEventRow",
    "BacktestMetricsRow",
    "BacktestRunRow",
    "BacktestTradeRow",
    "CompanyRow",
    "D",
    "DailyLossLockRow",
    "DailyPnlRow",
    "DataCompletenessRow",
    "DecisionRow",
    "FillRow",
    "FinancialMetricsRow",
    "FundamentalObservationRow",
    "FundamentalSeriesInstrumentRow",
    "FundamentalSeriesRow",
    "FundamentalSourceRow",
    "InsiderClusterRow",
    "InsiderTransactionRow",
    "InstitutionalChangeRow",
    "InstrumentImportEventRow",
    "InstrumentImportRunRow",
    "InstrumentRow",
    "KillSwitchRow",
    "MacroEventRow",
    "MacroSnapshotRow",
    "MacroSourceRow",
    "Migrator",
    "NewsImportEventRow",
    "NewsImportRunRow",
    "NewsItemRow",
    "NewsMessageEventRow",
    "NewsMessageInstrumentRow",
    "NewsMessageRow",
    "NewsSourceRow",
    "OptionsFlowRow",
    "OptionsSnapshotRow",
    "OrderRow",
    "PaperCanaryAccountRow",
    "PaperCanaryConflict",
    "PaperCanaryError",
    "PaperCanaryFillCommitResult",
    "PaperCanaryFillRow",
    "PaperCanaryOrderEventRow",
    "PaperCanaryOrderRow",
    "PaperCanaryPositionRow",
    "PaperCanaryReconciliationRow",
    "PaperCanaryRunRow",
    "PaperCanarySafetyError",
    "PaperCanaryStateError",
    "PositionRow",
    "ResearchDatasetEventRow",
    "ResearchDatasetRow",
    "ResearchIntelInputRow",
    "ResearchIntelOutcomeRow",
    "ResearchIntelSnapshotRow",
    "ResearchValidationRunRow",
    "RiskConfigRow",
    "RiskControlPolicyRow",
    "RiskEventRow",
    "RiskStateRow",
    "RuntimeStateRow",
    "SqlStore",
    "SqliteStore",
    "Store",
    "TraderPerformanceRow",
    "TraderPositionRow",
    "TraderRow",
    "ValuationRow",
    "money_str",
    "new_id",
    "open_sqlite",
    "open_store",
    "paper_canary_config_checksum",
    "paper_canary_request_checksum",
    "risk_config_token",
    "to_decimal",
    "utcnow_iso",
]


def open_store(url: str, *, migrate: bool = True):
    """Open the durable store for a URL. Postgres in production, SQLite locally/in tests."""
    if url.startswith(("postgres://", "postgresql://")):
        from .postgres_store import open_postgres
        return open_postgres(url, migrate=migrate)
    url = url.removeprefix("sqlite:///")
    return open_sqlite(url, migrate=migrate)
